version: '3'

services:
  frontend:
    image: gautampatil1/lofipomo-client:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: gautampatil1/lofipomo-server:latest
    ports:
      - "5000:5000"
    